"""Reference data for the visual guide; mechanisms are not product test results."""

CHECKED = "11 September 2026"

_REPO = "https://github.com/harshith0518/ProjectSemanticMemorySarvamAI/blob/dev/"
_BRIEF = _REPO + "docs/visual-guide-references.md#assignment-brief"

SOURCES = {
    "brief_scope": {
        "title": "Assignment scope: pp. 3-5",
        "url": _BRIEF,
        "kind": "BRIEF",
        "supports": "Includes factual, episodic and preference-level understanding; choose a useful product scope.",
        "limits": "The supplied Golden Goose brief, p. 3 under 'Begin with the use case', explicitly includes factual, episodic and preference-level understanding. Page 4 repeats that scope; p. 5 lists learned facts, preferences and episodes for review. The brief's broad product use of semantic memory is not the narrower cognitive taxonomy. Deferring automatic procedural learning is a project choice, not a brief prohibition. The PDF is in the parent planning workspace; this link points to its locator, not a public copy.",
    },
    "brief_product": {
        "title": "Assignment product requirements: p. 4",
        "url": _BRIEF,
        "kind": "BRIEF",
        "supports": "Requires an ordinary-user interface connected to actual state, persistence, retrieval and models.",
        "limits": "Page 4, 'Build the complete experience' and 'Build the system beneath it', requires a real end-to-end product. Transcript replay is allowed; ASR and production Kivi integration are unnecessary. A CLI, static guide or architectural proposal alone is insufficient. These are assignment requirements, not achieved milestones. The linked locator identifies the locally supplied brief.",
    },
    "brief_evaluation": {
        "title": "Assignment evaluation: pp. 4-6",
        "url": _BRIEF,
        "kind": "BRIEF",
        "supports": "Corpus, complete-pipeline evaluation, provenance, supported answers and abstention (pp. 4-6).",
        "limits": "Page 4 starts the approximately 500-record development requirement; p. 5 specifies raw/formatted variants, reproducible evaluation, inspectable sources and a separate reviewer corpus; p. 6 requires distributed recovery, supported answers and refusal to invent missing answers. The brief does not prescribe the project's 90% target, three repeats, schema or model shortlist. No product evaluation result follows from these requirements.",
    },
    "plan": {
        "title": "Kivi implementation plan",
        "url": _REPO + "PLAN.md",
        "kind": "PROJECT DECISION",
        "supports": "Proposed milestones, scope cuts, approval boundaries and the minimum complete reviewer journey.",
        "limits": "This project plan explains intended build order and acceptance gates. Work budgets are estimates, not delivery guarantees. The plan does not establish implementation, completed Part One submissions or approval of every later change. The linked GitHub dev-branch document can evolve after this diagram snapshot.",
    },
    "decisions": {
        "title": "Kivi requirements and open choices",
        "url": _REPO + "DECISIONS.md",
        "kind": "PROJECT DECISION",
        "supports": "Defines eligible evidence, Normal/Private, Correct/Forget and proposed implementation choices.",
        "limits": "This is the authoritative project distinction between agreed requirements and proposed architecture. Private and Forget are application promises to implement and test; external libraries do not establish them. Normal source retention and selective memory formation are different decisions. Source support does not guarantee real-world truth.",
    },
    "architecture": {
        "title": "Kivi architecture and model proposals",
        "url": _REPO + "ARCHITECTURE.md",
        "kind": "PROJECT DECISION",
        "supports": "Defines proposed records, pipelines, model boundaries, full shortlist and concurrency guards.",
        "limits": "The architecture is proposed, not implemented or benchmarked. It supplies Kivi-specific choices absent from external sources, including temporal reconciliation, typed model proposals, response publication and Private accounting. The main-model role is selected; endpoint access, smaller-model quality, cost and retention still need verification. Code owns authorization and database writes.",
    },
    "evaluation": {
        "title": "Kivi evaluation gates and race tests",
        "url": _REPO + "EVALUATION.md",
        "kind": "PROJECT DECISION",
        "supports": "Defines real-DB races, Private checks, repeated live cases, ablations and proposed quality gates.",
        "limits": "The 90% blind-success target, three live repeats and question counts are project acceptance choices, not benchmark standards or achieved results. Deterministic doubles exercise application contracts; they do not measure extraction quality. Live runs, failure reporting and semantic support review remain necessary. Private tests use synthetic content and must inspect actual data paths.",
    },
    "tracker": {
        "title": "Kivi current status and next action",
        "url": _REPO + "todo.md",
        "kind": "PROJECT DECISION",
        "supports": "Tracks completed, ongoing and pending work plus test, commit, push and verification workflow.",
        "limits": "The tracker is the evolving project status, not independent validation. Environment probes and documentation checks do not establish a running product. AI-assisted Part One reference drafts do not establish independent submissions. At this guide's planning snapshot S03 bootstrap remains subject to scope approval; recurring pushes of approved milestones are authorized.",
    },
    "langchain": {
        "title": "LangChain memory concepts",
        "url": "https://docs.langchain.com/oss/python/concepts/memory",
        "kind": "PRIMARY SOURCE",
        "supports": "Separates facts, experiences and instructions; explains thread state, stores and memory writing.",
        "limits": "The 'Long-term memory' table gives the narrower semantic/episodic/procedural taxonomy. It does not override the assignment's broader semantic-memory scope, require three databases or mandate LangGraph for Kivi. Persistent thread checkpoints are distinct from cross-thread memory. Its examples do not prove Kivi's privacy, reconciliation or retrieval quality.",
    },
    "prov": {
        "title": "W3C PROV: evidence and derivation",
        "url": "https://www.w3.org/TR/prov-overview/",
        "kind": "PRIMARY SOURCE",
        "supports": "Provides concepts for tracing entities, activities, attribution and derived information.",
        "limits": "PROV supplies a provenance vocabulary, not evidence that a statement is true. An existing source ID or derivation edge does not prove semantic entailment, trustworthy authorship or correct extraction. Kivi's span schema and invalidation protocol are application choices; using PROV concepts does not implement them automatically.",
    },
    "fowler": {
        "title": "Bitemporal history",
        "url": "https://martinfowler.com/articles/bitemporal-history.html",
        "kind": "PRIMARY SOURCE",
        "supports": "Distinguishes when information applies from when a system records or learns about it.",
        "limits": "This article explains temporal modeling, not an automatic truth-resolution algorithm. Capture, ingestion, event and validity times may differ; an unknown effective date cannot be inferred merely from ingestion order. A launch date is a claim value, not automatically its validity start. Kivi's successor and correction rules remain proposed application logic.",
    },
    "locking": {
        "title": "PostgreSQL explicit locking",
        "url": "https://www.postgresql.org/docs/current/explicit-locking.html",
        "kind": "PRIMARY SOURCE",
        "supports": "Documents transaction locks used to serialize shared policy validation and state changes.",
        "limits": "PostgreSQL documents locking primitives, not the complete Kivi Forget protocol. All relevant writers must use the same guard, recheck revisions inside the protected transaction and coordinate invalidation. Retrieval and response publication need their own defined revocation boundary. Verify with separate real database connections; already released response bytes cannot be recalled.",
    },
    "docker": {
        "title": "Docker Compose startup ordering",
        "url": "https://docs.docker.com/compose/how-tos/startup-order/",
        "kind": "PRIMARY SOURCE",
        "supports": "Explains dependency ordering, healthy-service conditions and successful one-shot completion.",
        "limits": "Starting a container is not proof the service is ready. Health and completion conditions can support a database-to-migration-to-application sequence, but migrations, volume isolation and failure behavior require implementation and checks. This guide does not establish that Kivi's Compose stack or project database exists.",
    },
    "fastapi": {
        "title": "FastAPI application containers",
        "url": "https://fastapi.tiangolo.com/deployment/docker/",
        "kind": "PRIMARY SOURCE",
        "supports": "Explains building and running a FastAPI application in a container image.",
        "limits": "Container deployment guidance supports the proposed packaging method. It does not prescribe Kivi's shared API/CLI/worker services, guarantee isolation or supply memory semantics. Dependency and image versions must be pinned and tested during approved bootstrap; the guide is not proof of a working backend.",
    },
    "rrf": {
        "title": "Reciprocal Rank Fusion paper",
        "url": "https://cormack.uwaterloo.ca/cormacksigir09-rrf.pdf",
        "kind": "PRIMARY SOURCE",
        "supports": "Combines candidate rankings using reciprocal rank contributions; motivates the k=60 example.",
        "limits": "RRF fuses ranked lists; its score is not a probability of truth or relevance. The diagram's k=60 and one-based ranks define the illustrated calculation, not a locally tuned optimum. A missing candidate contributes nothing from that list. Permission, exclusion and time checks remain mandatory; retrieval effectiveness must be measured on Kivi's questions.",
    },
    "pgvector": {
        "title": "pgvector: exact and hybrid search",
        "url": "https://github.com/pgvector/pgvector",
        "kind": "PRIMARY SOURCE",
        "supports": "Documents exact/approximate vectors and full-text hybrid search with fusion or reranking.",
        "limits": "pgvector is a retrieval component, not a memory-management system. PostgreSQL full-text ranking is not automatically BM25. Approximate indexes may miss candidates; exact search is a proposed starting point, not a measured latency guarantee. Five hundred observations may create more than five hundred claims or chunks. Indexes do not replace canonical evidence or exclusion checks.",
    },
    "anthropic": {
        "title": "Anthropic contextual retrieval",
        "url": "https://www.anthropic.com/engineering/contextual-retrieval",
        "kind": "PRIMARY SOURCE",
        "supports": "Explains preserving chunk context and combining lexical, dense and reranking mechanisms.",
        "limits": "Anthropic's engineering experiments motivate retrieval mechanisms, not a verified Kivi architecture or expected improvement. Contextualization may add model cost and can introduce unsupported interpretation. The Atlas example is synthetic and separate. Preserve original passages and evaluate any contextualized representation rather than transferring reported benchmark gains.",
    },
    "example": {
        "title": "Synthetic Atlas / Mira fixtures",
        "url": _REPO + "README.md#using-the-visual-guide",
        "kind": "SYNTHETIC EXAMPLE",
        "supports": "Illustrates changed plans, scoped preferences, reported actions, uncertainty and exact sources.",
        "limits": "The eight source records live at ../reference-examples/sample-dictations.jsonl in the parent planning workspace, with separate evaluator-only labels. They are not bundled application data at this checkpoint and are not external validation. The README gives their location. Preserve raw/formatted variants as one observation; never ingest the evaluator labels. Illustrated outcomes are expectations, not measured model results.",
    },
    "deepseek": {
        "title": "NVIDIA DeepSeek dated endpoint",
        "url": "https://build.nvidia.com/deepseek-ai/deepseek-v4-pro-0813",
        "kind": "PRIMARY SOURCE",
        "supports": "Documents the candidate hosted DeepSeek endpoint for the selected main-model role.",
        "limits": "A listed endpoint does not establish account access, quotas, acceptable retention, schema enforcement or Kivi task quality. Verify configured and returned model IDs, cost and no-training settings before live calls. The user's main-model role choice is recorded in project architecture; endpoint availability can change after this check.",
    },
    "lightning": {
        "title": "Nemotron Lightning model card",
        "url": "https://huggingface.co/nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
        "kind": "PRIMARY SOURCE",
        "supports": "Describes a candidate model for bounded typed proposals, including its sparse architecture.",
        "limits": "The model card does not prove hosted endpoint behavior, multilingual extraction faithfulness or Kivi cost savings. Total parameters and active parameters are different; active count is not the required local memory footprint. Tools and structured-output training do not guarantee valid, supported proposals. The full untested shortlist and provider boundaries are project architecture choices.",
    },
    "selfrefine": {
        "title": "Self-Refine: feedback and revision",
        "url": "https://arxiv.org/abs/2303.17651",
        "kind": "PRIMARY SOURCE",
        "supports": "Studies iterative feedback and refinement of model outputs without additional model training.",
        "limits": "Self-generated critique is not guaranteed correct and may preserve or amplify an error. This paper does not prove autonomous root-cause diagnosis, factual memory correction or safe procedural learning for Kivi. Kivi proposes inspecting observable evidence and repairing the demonstrated failing layer with a bounded retry and regression case.",
    },
    "reflexion": {
        "title": "Reflexion: verbal feedback memory",
        "url": "https://arxiv.org/abs/2303.11366",
        "kind": "PRIMARY SOURCE",
        "supports": "Studies agents using linguistic feedback and stored reflections to improve later attempts.",
        "limits": "Reflexion is not a guarantee that an agent learns the right lesson or updates model weights. Reported experiments do not validate Kivi's user-feedback loop. A disliked reply is not automatically a corrected fact or universal preference. Automatic prompt or skill rewriting is deferred; supported, scoped changes remain controlled application operations.",
    },
    "longmemeval": {
        "title": "LongMemEval benchmark repository",
        "url": "https://github.com/xiaowu0162/LongMemEval",
        "kind": "PRIMARY SOURCE",
        "supports": "Offers long-term memory tasks covering extraction, updates, temporal reasoning and abstention.",
        "limits": "Benchmark task families inform challenge design; the repository does not provide a Kivi result. Public benchmark questions are not the assignment's approximately 500 source observations. The project's three repeats, blind question count and 90% success gate are separate choices. Do not equate a vendor's benchmark score with local product performance.",
    },
    "irbook": {
        "title": "IR textbook: precision and recall",
        "url": "https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-unranked-retrieval-sets-1.html",
        "kind": "PRIMARY SOURCE",
        "supports": "Defines precision and recall for retrieved sets relative to judged relevance.",
        "limits": "Retrieval relevance metrics require an explicit ground-truth set and do not alone measure factual support, task completion, correct temporal interpretation or privacy. Kivi should report evidence coverage and supported task success separately. Small samples and incomplete labels limit the conclusions; all reported values must come from actual evaluation runs.",
    },
}

PAGE_REFS = {
    1: ("brief_scope", "plan", "decisions"),
    2: ("brief_scope", "langchain", "architecture"),
    3: ("docker", "fastapi", "architecture"),
    4: ("prov", "brief_evaluation", "architecture"),
    5: ("fowler", "prov", "architecture"),
    6: ("langchain", "locking", "architecture"),
    7: ("fowler", "prov", "architecture"),
    8: ("langchain", "decisions", "architecture"),
    9: ("rrf", "pgvector", "architecture"),
    10: ("anthropic", "prov", "example"),
    11: ("deepseek", "lightning", "architecture"),
    12: ("decisions", "architecture", "evaluation"),
    13: ("prov", "locking", "decisions"),
    14: ("locking", "architecture", "evaluation"),
    15: ("selfrefine", "reflexion", "architecture"),
    16: ("longmemeval", "irbook", "brief_evaluation"),
    17: ("pgvector", "docker", "decisions"),
    18: ("brief_product", "plan", "tracker"),
}
